//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalIndex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalSpecialityEnum
    {
        public ClinicalSpecialityEnum()
        {
            this.Clinics = new HashSet<Clinic>();
            this.Hospitals = new HashSet<Hospital>();
            this.MedicalCenters = new HashSet<MedicalCenter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Clinic> Clinics { get; set; }
        public virtual ICollection<Hospital> Hospitals { get; set; }
        public virtual ICollection<MedicalCenter> MedicalCenters { get; set; }
    }
}
