//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalIndex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCenter : Facility
    {
        public MedicalCenter()
        {
            this.ClinicalSpecialityEnum = new HashSet<ClinicalSpecialityEnum>();
        }
    
        public int MedicalCenterId { get; set; }
    
        public virtual ICollection<ClinicalSpecialityEnum> ClinicalSpecialityEnum { get; set; }
    }
}
