//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalIndex.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIEntitiesContainer : DbContext
    {
        public MIEntitiesContainer()
            : base("name=MIEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<ClinicalSpecialityEnum> ClinicalSpecialityEnums { get; set; }
        public DbSet<Neighborhood> Neighborhoods { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Phone> Phones { get; set; }
        public DbSet<FacilityTypeEnum> FacilityTypeEnums { get; set; }
    }
}
