USE [master]
GO

/****** Object:  Database [MedIndex]    Script Date: 01/31/2013 18:52:21 ******/
CREATE DATABASE [MedIndex] ON  PRIMARY 
( NAME = N'MedIndex', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\MedIndex.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MedIndex_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\MedIndex.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MedIndex] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MedIndex].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MedIndex] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [MedIndex] SET ANSI_NULLS ON 
GO

ALTER DATABASE [MedIndex] SET ANSI_PADDING ON 
GO

ALTER DATABASE [MedIndex] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [MedIndex] SET ARITHABORT ON 
GO

ALTER DATABASE [MedIndex] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MedIndex] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MedIndex] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MedIndex] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MedIndex] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MedIndex] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [MedIndex] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [MedIndex] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MedIndex] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [MedIndex] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MedIndex] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MedIndex] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MedIndex] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MedIndex] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MedIndex] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MedIndex] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MedIndex] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MedIndex] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MedIndex] SET  READ_WRITE 
GO

ALTER DATABASE [MedIndex] SET RECOVERY FULL 
GO

ALTER DATABASE [MedIndex] SET  MULTI_USER 
GO

ALTER DATABASE [MedIndex] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MedIndex] SET DB_CHAINING OFF 
GO

